export const CATEGORIES = [
  { name: "AI Tools", value: "$10K" },
  { name: "Dropshipping", value: "$8K" },
  { name: "Instagram Growth", value: "$5K" },
  { name: "Video Editing", value: "$4.5K" },
  { name: "Canva Templates", value: "$3K" },
  { name: "SaaS Starters", value: "$12K" },
  { name: "Copywriting Hub", value: "$6K" },
  { name: "Crypto Guides", value: "$9K" },
  { name: "E-commerce SEO", value: "$7K" },
  { name: "Graphic Design", value: "$4K" },
  { name: "Marketing Kits", value: "$11K" },
  { name: "Freelance Toolkit", value: "$3.5K" },
  { name: "Stock Footage", value: "$15K" },
  { name: "Music Production", value: "$8.5K" },
  { name: "Web Dev Assets", value: "$20K" },
  { name: "App Blueprints", value: "$18K" },
  { name: "Pinterest Sales", value: "$4.2K" },
  { name: "Youtube Growth", value: "$5.8K" },
  { name: "TikTok Masterclass", value: "$6.5K" },
  { name: "Productivity Pack", value: "$2.5K" },
  { name: "Email Marketing", value: "$7.2K" },
  { name: "Discord Setup", value: "$3.8K" },
  { name: "Podcast Kit", value: "$5.2K" },
  { name: "Shopify Themes", value: "$9.5K" },
  { name: "FB Ads Vault", value: "$10.5K" },
  { name: "Google Ads Hub", value: "$8.8K" },
  { name: "UGC Roadmap", value: "$4.7K" },
  { name: "Influencer Kit", value: "$3.2K" },
  { name: "No-Code Apps", value: "$13K" },
  { name: "NFT Art Packs", value: "$11.5K" },
  { name: "UI/UX Kits", value: "$14K" },
  { name: "Icon Sets", value: "$2.2K" },
  { name: "Font Library", value: "$3.6K" },
  { name: "Mockup Engine", value: "$5.5K" },
  { name: "3D Models", value: "$12.5K" },
  { name: "Unity Assets", value: "$16K" },
  { name: "Unreal Engine", value: "$19K" },
  { name: "Python Scripts", value: "$7.6K" },
  { name: "JS Libraries", value: "$8.2K" },
  { name: "Docker Configs", value: "$4.4K" },
  { name: "Cloud Templates", value: "$10.2K" },
  { name: "Cybersecurity", value: "$17K" },
  { name: "Fintech Scripts", value: "$22K" },
  { name: "Real Estate Kit", value: "$6.8K" },
  { name: "Health & Fitness", value: "$3.4K" },
  { name: "Yoga Masterclass", value: "$2.8K" },
  { name: "Biohacking Hub", value: "$5.7K" },
  { name: "Meditation Audio", value: "$4.3K" },
  { name: "Self-Help Library", value: "$9.8K" },
  { name: "Business Letters", value: "$2.1K" },
  { name: "Legal Templates", value: "$11.2K" },
  { name: "HR Documents", value: "$4.6K" },
  { name: "Startup Pitch", value: "$13.5K" },
  { name: "Investor List", value: "$25K" },
  { name: "Sales Scripts", value: "$6.2K" },
  { name: "Closing Techniques", value: "$8.4K" },
  { name: "Cold Email Hub", value: "$5.3K" },
  { name: "CRM Templates", value: "$7.1K" },
  { name: "Accounting Kit", value: "$4.8K" },
  { name: "Tax Strategies", value: "$12.2K" },
  { name: "Personal Brand", value: "$9.2K" },
  { name: "Coaching Setup", value: "$10.8K" },
  { name: "Consulting Kit", value: "$14.5K" },
  { name: "Agency Manual", value: "$15.5K" },
  { name: "Outsourcing Kit", value: "$6.4K" },
  { name: "Virtual Assistant", value: "$3.1K" },
  { name: "Automation Flows", value: "$18.5K" },
  { name: "Zapier Secrets", value: "$4.1K" },
  { name: "Make.com Vault", value: "$5.6K" },
  { name: "ChatGPT Prompts", value: "$1.5K" },
  { name: "LLM Training", value: "$20.5K" },
  { name: "Midjourney Hub", value: "$2.7K" },
  { name: "Stable Diffusion", value: "$6.1K" },
  { name: "Prompt Engineer", value: "$10.1K" },
  { name: "Airtable Systems", value: "$8.7K" },
  { name: "Notion Vault", value: "$4.2K" },
  { name: "Obsidian Graphs", value: "$3.3K" },
  { name: "Productivity", value: "$2.2K" },
  { name: "Bio-Link Kits", value: "$1.8K" },
  { name: "Twitter Sales", value: "$4.9K" },
  { name: "Ghostwriting Hub", value: "$11.7K" },
  { name: "Kindle Roadmap", value: "$7.5K" },
  { name: "Etsy Blueprints", value: "$5.1K" },
  { name: "eBay Arbitrage", value: "$3.9K" },
  { name: "Amazon FBA", value: "$16.5K" },
  { name: "Wholesale Hub", value: "$12.8K" },
  { name: "Property Guide", value: "$14.2K" },
  { name: "Rental Arbitrage", value: "$9.4K" },
  { name: "Airbnb Ops", value: "$8.1K" },
  { name: "Turo Handbook", value: "$5.4K" },
  { name: "Credit Repair", value: "$10.4K" },
  { name: "Stock Market", value: "$18.2K" },
  { name: "Options Trading", value: "$22.5K" },
  { name: "Day Trading Hub", value: "$19.5K" },
  { name: "Swing Trading", value: "$15.2K" },
  { name: "Forex Masterly", value: "$17.5K" },
  { name: "Commodities Kit", value: "$13.8K" },
  { name: "Hedge Fund Hub", value: "$30K" },
  { name: "Family Office", value: "$45K" },
  { name: "Wealth Secrets", value: "$100K" },
];

export const TESTIMONIALS = [
  { name: "Alex R.", text: "Made my first $500 in 3 days using the Dropshipping vault. Insane value.", role: "Digital Entrepreneur" },
  { name: "Sarah J.", text: "Best investment ever. The AI tools alone saved me hundreds of hours of work.", role: "Content Creator" },
  { name: "Michael T.", text: "I was skeptical, but the quality of these assets is enterprise-grade. Wow.", role: "Agency Owner" },
  { name: "Elena S.", text: "Unlocked the 'Free Access' in time. This is literally gold mine for creators.", role: "Graphic Designer" },
  { name: "David K.", text: "The weekly updates keep me ahead of the curve. Scaling my SaaS now.", role: "Indie Hacker" }
];

export const PRODUCT_IMAGES = [
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392196/file_0000000062a871fa9af5912649424848_tiq0gi.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392197/file_00000000082871fab3d15c0712a5a5fe_bgmihy.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392200/file_00000000d77c71faa4e3cfad52ef1c39_rejx4m.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392200/file_00000000a1e871fa879dce32ebc70f76_tdrnho.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392201/file_00000000f43071fabad287bc3b0322dd_rhnjay.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392202/file_00000000cc9471faa63bf43bb7e6c5eb_ck9tzh.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392212/file_00000000749c71faa585452dfb1f4fab_p8ccf5.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392212/file_0000000033d871fab111515f40c0d08d_ju9bzt.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392214/file_00000000cd5471fa97a07fda6e989d0b_aitcxr.png",
  "https://res.cloudinary.com/globalglaz-com/image/upload/v1776392214/file_000000006f8071fa95e487cef423a15a_fz2flg.png"
];

